name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Initiate JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Tests
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: current
          arguments: test -PsonatypeUsername=${{secrets.SONATYPE_USERNAME}} -PsonatypePassword=${{secrets.SONATYPE_PASSWORD}}